version: '3'
services:
    server-service:
        image: node:16
        container_name: auth_server_delete
        volumes:
            - ./node_modules:/node_modules
            - ./server:/server
            - ./interfaces:/interfaces
            - ./tsconfig.json:/tsconfig.json
            - ./package.json:/package.json
        ports:
            - '3001:3001'
        working_dir: /
        command: npm run server:dev --project server/tsconfig.json -r tsconfig-paths/register server/index.ts
        env_file: .env

    mongodb:
        image: mongo:5
        container_name: auth_mongodb_delete
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: fullstack
            MONGO_INITDB_ROOT_PASSWORD: nioka20
